[theme]
primaryColor = "#EAA385"          # The accent color for buttons and interactive elements (outer lines)
backgroundColor = "#0d213c"       # The main background color
secondaryBackgroundColor = "#212426" # Sidebar and widget background color
textColor = "#F1F5F9"             # Main text color
font = "sans serif"               # Options: "sans serif", "serif", or "monospace"